name: embryostage-napari
channels:
  - bioconda
  - conda-forge
dependencies:
  - alabaster=0.7.13
  - aom=3.6.1
  - app-model=0.2.2
  - appdirs=1.4.4
  - appnope=0.1.3
  - asciitree=0.3.3
  - asttokens=2.4.1
  - attrs=23.1.0
  - babel=2.13.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-blosc2=2.11.1
  - ca-certificates=2023.7.22
  - cachey=0.2.1
  - certifi=2023.7.22
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.1.4
  - cytoolz=0.12.2
  - dask-core=2023.10.1
  - dav1d=1.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - docstring_parser=0.15
  - docutils=0.17.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - fasteners=0.17.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freetype-py=2.4.0
  - fsspec=2023.10.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - heapdict=1.0.1
  - hsluv=5.0.4
  - icu=73.2
  - idna=3.4
  - imagecodecs=2023.9.18
  - imageio=2.31.5
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - in-n-out=0.1.9
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy_loader=0.3
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.1.2
  - libavif16=1.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=16.0
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=17.0.4
  - locket=1.0.0
  - lz4-c=1.9.4
  - magicgui=0.8.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - msgpack-python=1.0.6
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - napari=0.4.18
  - napari-console=0.0.9
  - napari-plugin-engine=0.2.0
  - napari-svg=0.1.10
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=3.2.1
  - npe2=0.7.3
  - nspr=4.35
  - nss=3.94
  - numcodecs=0.12.1
  - numpy=1.26.0
  - numpydoc=1.5.0
  - openjpeg=2.5.0
  - openssl=3.1.4
  - packaging=23.2
  - pandas=2.1.2
  - parso=0.8.3
  - partd=1.4.1
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pint=0.22
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - ply=3.11
  - pooch=1.8.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - psygnal=0.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyconify=0.1.6
  - pydantic=1.10.13
  - pygments=2.16.1
  - pyopengl=3.1.6
  - pyproject_hooks=1.0.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-build=1.0.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - qtconsole-base=5.5.0
  - qtpy=2.4.1
  - rav1e=0.6.6
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rich=13.6.0
  - rpds-py=0.12.0
  - scikit-image=0.22.0
  - scipy=1.11.3
  - setuptools=68.2.2
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - snowballstemmer=2.2.0
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - stack_data=0.6.2
  - superqt=0.6.1
  - svt-av1=1.7.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomli-w=1.0.0
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - typer=0.9.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.0.7
  - vispy=0.12.2
  - wcwidth=0.2.9
  - wheel=0.41.3
  - wrapt=1.15.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - aiobotocore==2.7.0
      - aiohttp==3.8.6
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - blosc2==2.2.9
      - botocore==1.31.64
      - cachetools==5.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - distributed==2023.10.1
      - embryostage==0.1.dev131+g142f5c6
      - filelock==3.13.1
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.2
      - iohub==0.1.0.dev4
      - jmespath==1.0.1
      - joblib==1.3.2
      - lightning==2.1.0
      - lightning-utilities==0.9.0
      - markdown==3.5.1
      - matplotlib==3.8.1
      - monai==1.3.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - napari-ome-zarr==0.5.2
      - natsort==8.4.0
      - nd2==0.8.0
      - ndindex==1.7
      - ndtiff==2.2.1
      - oauthlib==3.2.2
      - ome-zarr==0.8.2
      - protobuf==4.23.4
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - pytorch-lightning==2.1.0
      - pytorch-model-summary==0.1.2
      - requests-oauthlib==1.3.1
      - resource-backed-dask-array==0.1.0
      - rsa==4.9
      - s3fs==2023.10.0
      - scikit-learn==1.3.2
      - seaborn==0.13.0
      - sortedcontainers==2.4.0
      - sympy==1.12
      - tblib==3.0.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - tifffile==2023.2.28
      - torch==2.1.0
      - torchmetrics==1.2.0
      - torchvision==0.16.0
      - werkzeug==3.0.1
      - yarl==1.9.2
      - zarr==2.15.0
      - zict==3.0.0
